/********************************************************************************
** Form generated from reading UI file 'admin.ui'
**
** Created by: Qt User Interface Compiler version 5.6.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ADMIN_H
#define UI_ADMIN_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Admin
{
public:
    QAction *actionLogout;
    QWidget *centralwidget;
    QTabWidget *admintabs;
    QWidget *UserData;
    QLabel *picture;
    QPushButton *changephoto;
    QPushButton *editprofile;
    QGroupBox *groupBox;
    QLabel *role_label;
    QLabel *role;
    QLabel *fine_label;
    QLabel *fine;
    QLabel *username_label;
    QLabel *username;
    QLabel *email;
    QLabel *id;
    QLabel *name;
    QLabel *name_label;
    QLabel *email_label;
    QLabel *id_label;
    QPushButton *deleteme;
    QWidget *tab_2;
    QLabel *findid_label;
    QLineEdit *findid;
    QPushButton *findid_button;
    QLabel *picture_usr;
    QGroupBox *groupBox_2;
    QLabel *role_label_usr;
    QLabel *role_usr;
    QLabel *fine_label_usr;
    QLabel *fine_usr;
    QLabel *username_label_usr;
    QLabel *username_usr;
    QLabel *email_usr;
    QLabel *id_usr;
    QLabel *name_usr;
    QLabel *fullname_label_usr;
    QLabel *email_label_usr;
    QLabel *id_label_usr;
    QLabel *bookamt_label_usr;
    QFrame *line;
    QLabel *bookamt_usr;
    QLabel *booklim_label_usr;
    QLabel *booklim_usr;
    QPushButton *changephoto_2;
    QPushButton *editdata;
    QGroupBox *advanceGrp;
    QSpinBox *booklim;
    QLabel *label;
    QPushButton *apply;
    QSpinBox *fine_spin;
    QLabel *label_4;
    QSpinBox *borrow_spin;
    QLabel *label_3;
    QPushButton *deleteusr;
    QPushButton *clear;
    QWidget *tab;
    QLabel *picture_book;
    QPushButton *changebookphoto;
    QGroupBox *groupBox_3;
    QLabel *bookname_label;
    QLineEdit *bookname;
    QLabel *ISBN_label;
    QLabel *bookid_labe;
    QLabel *bookid;
    QLineEdit *isbn;
    QPushButton *edit;
    QPushButton *applyedit;
    QLabel *author_label;
    QLineEdit *author;
    QLabel *loan_label;
    QSpinBox *loan;
    QLabel *loan_label_2;
    QLabel *loaner_label;
    QLabel *loaner;
    QLabel *price_label;
    QSpinBox *price;
    QLabel *price_label_2;
    QLineEdit *searchbook;
    QLabel *label_2;
    QPushButton *search;
    QPushButton *delete_2;
    QPushButton *addbook;
    QPushButton *reserve;
    QPushButton *clearloan;
    QWidget *tab_3;
    QLabel *usrreg;
    QLabel *usrphoto;
    QLabel *usrinfo;
    QPushButton *usrreg_toggle;
    QLabel *label_5;
    QPushButton *usrinfo_toggle;
    QPushButton *usrphoto_toggle;
    QLabel *welcome;
    QPushButton *logout;
    QMenuBar *menubar;

    void setupUi(QMainWindow *Admin)
    {
        if (Admin->objectName().isEmpty())
            Admin->setObjectName(QStringLiteral("Admin"));
        Admin->resize(455, 442);
        actionLogout = new QAction(Admin);
        actionLogout->setObjectName(QStringLiteral("actionLogout"));
        centralwidget = new QWidget(Admin);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        admintabs = new QTabWidget(centralwidget);
        admintabs->setObjectName(QStringLiteral("admintabs"));
        admintabs->setGeometry(QRect(10, 10, 431, 391));
        admintabs->setAutoFillBackground(true);
        UserData = new QWidget();
        UserData->setObjectName(QStringLiteral("UserData"));
        picture = new QLabel(UserData);
        picture->setObjectName(QStringLiteral("picture"));
        picture->setGeometry(QRect(20, 20, 161, 201));
        picture->setFrameShape(QFrame::Box);
        changephoto = new QPushButton(UserData);
        changephoto->setObjectName(QStringLiteral("changephoto"));
        changephoto->setGeometry(QRect(20, 230, 81, 23));
        editprofile = new QPushButton(UserData);
        editprofile->setObjectName(QStringLiteral("editprofile"));
        editprofile->setGeometry(QRect(110, 230, 75, 23));
        groupBox = new QGroupBox(UserData);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(200, 20, 211, 161));
        role_label = new QLabel(groupBox);
        role_label->setObjectName(QStringLiteral("role_label"));
        role_label->setGeometry(QRect(10, 130, 51, 16));
        role = new QLabel(groupBox);
        role->setObjectName(QStringLiteral("role"));
        role->setGeometry(QRect(70, 130, 71, 16));
        fine_label = new QLabel(groupBox);
        fine_label->setObjectName(QStringLiteral("fine_label"));
        fine_label->setGeometry(QRect(10, 110, 47, 13));
        fine = new QLabel(groupBox);
        fine->setObjectName(QStringLiteral("fine"));
        fine->setGeometry(QRect(70, 110, 47, 13));
        username_label = new QLabel(groupBox);
        username_label->setObjectName(QStringLiteral("username_label"));
        username_label->setGeometry(QRect(10, 80, 51, 16));
        username = new QLabel(groupBox);
        username->setObjectName(QStringLiteral("username"));
        username->setGeometry(QRect(70, 80, 111, 16));
        email = new QLabel(groupBox);
        email->setObjectName(QStringLiteral("email"));
        email->setGeometry(QRect(70, 60, 131, 16));
        id = new QLabel(groupBox);
        id->setObjectName(QStringLiteral("id"));
        id->setGeometry(QRect(70, 40, 91, 16));
        name = new QLabel(groupBox);
        name->setObjectName(QStringLiteral("name"));
        name->setGeometry(QRect(70, 20, 131, 16));
        name_label = new QLabel(groupBox);
        name_label->setObjectName(QStringLiteral("name_label"));
        name_label->setGeometry(QRect(10, 20, 51, 16));
        email_label = new QLabel(groupBox);
        email_label->setObjectName(QStringLiteral("email_label"));
        email_label->setGeometry(QRect(10, 60, 47, 13));
        id_label = new QLabel(groupBox);
        id_label->setObjectName(QStringLiteral("id_label"));
        id_label->setGeometry(QRect(10, 40, 61, 16));
        deleteme = new QPushButton(UserData);
        deleteme->setObjectName(QStringLiteral("deleteme"));
        deleteme->setGeometry(QRect(50, 260, 101, 23));
        admintabs->addTab(UserData, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        findid_label = new QLabel(tab_2);
        findid_label->setObjectName(QStringLiteral("findid_label"));
        findid_label->setGeometry(QRect(20, 20, 91, 16));
        findid = new QLineEdit(tab_2);
        findid->setObjectName(QStringLiteral("findid"));
        findid->setGeometry(QRect(120, 20, 131, 20));
        findid_button = new QPushButton(tab_2);
        findid_button->setObjectName(QStringLiteral("findid_button"));
        findid_button->setGeometry(QRect(270, 20, 75, 23));
        picture_usr = new QLabel(tab_2);
        picture_usr->setObjectName(QStringLiteral("picture_usr"));
        picture_usr->setGeometry(QRect(20, 60, 161, 201));
        picture_usr->setFrameShape(QFrame::Box);
        groupBox_2 = new QGroupBox(tab_2);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(190, 60, 211, 201));
        role_label_usr = new QLabel(groupBox_2);
        role_label_usr->setObjectName(QStringLiteral("role_label_usr"));
        role_label_usr->setGeometry(QRect(10, 100, 51, 16));
        role_usr = new QLabel(groupBox_2);
        role_usr->setObjectName(QStringLiteral("role_usr"));
        role_usr->setGeometry(QRect(70, 100, 71, 16));
        fine_label_usr = new QLabel(groupBox_2);
        fine_label_usr->setObjectName(QStringLiteral("fine_label_usr"));
        fine_label_usr->setGeometry(QRect(10, 140, 47, 13));
        fine_usr = new QLabel(groupBox_2);
        fine_usr->setObjectName(QStringLiteral("fine_usr"));
        fine_usr->setGeometry(QRect(70, 140, 47, 13));
        username_label_usr = new QLabel(groupBox_2);
        username_label_usr->setObjectName(QStringLiteral("username_label_usr"));
        username_label_usr->setGeometry(QRect(10, 80, 51, 16));
        username_usr = new QLabel(groupBox_2);
        username_usr->setObjectName(QStringLiteral("username_usr"));
        username_usr->setGeometry(QRect(70, 80, 111, 16));
        email_usr = new QLabel(groupBox_2);
        email_usr->setObjectName(QStringLiteral("email_usr"));
        email_usr->setGeometry(QRect(70, 60, 131, 16));
        id_usr = new QLabel(groupBox_2);
        id_usr->setObjectName(QStringLiteral("id_usr"));
        id_usr->setGeometry(QRect(70, 40, 91, 16));
        name_usr = new QLabel(groupBox_2);
        name_usr->setObjectName(QStringLiteral("name_usr"));
        name_usr->setGeometry(QRect(70, 20, 131, 16));
        fullname_label_usr = new QLabel(groupBox_2);
        fullname_label_usr->setObjectName(QStringLiteral("fullname_label_usr"));
        fullname_label_usr->setGeometry(QRect(10, 20, 51, 16));
        email_label_usr = new QLabel(groupBox_2);
        email_label_usr->setObjectName(QStringLiteral("email_label_usr"));
        email_label_usr->setGeometry(QRect(10, 60, 47, 13));
        id_label_usr = new QLabel(groupBox_2);
        id_label_usr->setObjectName(QStringLiteral("id_label_usr"));
        id_label_usr->setGeometry(QRect(10, 40, 61, 16));
        bookamt_label_usr = new QLabel(groupBox_2);
        bookamt_label_usr->setObjectName(QStringLiteral("bookamt_label_usr"));
        bookamt_label_usr->setGeometry(QRect(10, 160, 81, 16));
        line = new QFrame(groupBox_2);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(10, 120, 191, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        bookamt_usr = new QLabel(groupBox_2);
        bookamt_usr->setObjectName(QStringLiteral("bookamt_usr"));
        bookamt_usr->setGeometry(QRect(90, 160, 101, 16));
        booklim_label_usr = new QLabel(groupBox_2);
        booklim_label_usr->setObjectName(QStringLiteral("booklim_label_usr"));
        booklim_label_usr->setGeometry(QRect(10, 180, 51, 16));
        booklim_usr = new QLabel(groupBox_2);
        booklim_usr->setObjectName(QStringLiteral("booklim_usr"));
        booklim_usr->setGeometry(QRect(70, 180, 171, 16));
        changephoto_2 = new QPushButton(tab_2);
        changephoto_2->setObjectName(QStringLiteral("changephoto_2"));
        changephoto_2->setEnabled(false);
        changephoto_2->setGeometry(QRect(20, 270, 81, 23));
        editdata = new QPushButton(tab_2);
        editdata->setObjectName(QStringLiteral("editdata"));
        editdata->setEnabled(false);
        editdata->setGeometry(QRect(110, 270, 75, 23));
        advanceGrp = new QGroupBox(tab_2);
        advanceGrp->setObjectName(QStringLiteral("advanceGrp"));
        advanceGrp->setEnabled(false);
        advanceGrp->setGeometry(QRect(190, 270, 211, 91));
        booklim = new QSpinBox(advanceGrp);
        booklim->setObjectName(QStringLiteral("booklim"));
        booklim->setGeometry(QRect(80, 20, 42, 22));
        label = new QLabel(advanceGrp);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 20, 71, 16));
        apply = new QPushButton(advanceGrp);
        apply->setObjectName(QStringLiteral("apply"));
        apply->setGeometry(QRect(130, 40, 75, 23));
        fine_spin = new QSpinBox(advanceGrp);
        fine_spin->setObjectName(QStringLiteral("fine_spin"));
        fine_spin->setGeometry(QRect(80, 40, 42, 22));
        fine_spin->setMaximum(10000);
        label_4 = new QLabel(advanceGrp);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 60, 71, 16));
        borrow_spin = new QSpinBox(advanceGrp);
        borrow_spin->setObjectName(QStringLiteral("borrow_spin"));
        borrow_spin->setGeometry(QRect(80, 60, 42, 22));
        borrow_spin->setMaximum(1000);
        borrow_spin->setSingleStep(1);
        label_3 = new QLabel(advanceGrp);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 40, 61, 16));
        deleteusr = new QPushButton(tab_2);
        deleteusr->setObjectName(QStringLiteral("deleteusr"));
        deleteusr->setEnabled(false);
        deleteusr->setGeometry(QRect(60, 300, 75, 23));
        clear = new QPushButton(tab_2);
        clear->setObjectName(QStringLiteral("clear"));
        clear->setEnabled(false);
        clear->setGeometry(QRect(20, 330, 151, 23));
        admintabs->addTab(tab_2, QString());
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        picture_book = new QLabel(tab);
        picture_book->setObjectName(QStringLiteral("picture_book"));
        picture_book->setGeometry(QRect(250, 60, 161, 201));
        picture_book->setFrameShape(QFrame::Box);
        changebookphoto = new QPushButton(tab);
        changebookphoto->setObjectName(QStringLiteral("changebookphoto"));
        changebookphoto->setEnabled(false);
        changebookphoto->setGeometry(QRect(290, 270, 81, 23));
        groupBox_3 = new QGroupBox(tab);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setEnabled(false);
        groupBox_3->setGeometry(QRect(10, 50, 231, 291));
        bookname_label = new QLabel(groupBox_3);
        bookname_label->setObjectName(QStringLiteral("bookname_label"));
        bookname_label->setGeometry(QRect(10, 40, 71, 16));
        bookname = new QLineEdit(groupBox_3);
        bookname->setObjectName(QStringLiteral("bookname"));
        bookname->setEnabled(false);
        bookname->setGeometry(QRect(80, 40, 131, 20));
        ISBN_label = new QLabel(groupBox_3);
        ISBN_label->setObjectName(QStringLiteral("ISBN_label"));
        ISBN_label->setGeometry(QRect(10, 70, 61, 16));
        bookid_labe = new QLabel(groupBox_3);
        bookid_labe->setObjectName(QStringLiteral("bookid_labe"));
        bookid_labe->setGeometry(QRect(10, 20, 61, 16));
        bookid = new QLabel(groupBox_3);
        bookid->setObjectName(QStringLiteral("bookid"));
        bookid->setGeometry(QRect(80, 20, 131, 16));
        isbn = new QLineEdit(groupBox_3);
        isbn->setObjectName(QStringLiteral("isbn"));
        isbn->setEnabled(false);
        isbn->setGeometry(QRect(80, 70, 131, 20));
        edit = new QPushButton(groupBox_3);
        edit->setObjectName(QStringLiteral("edit"));
        edit->setGeometry(QRect(40, 260, 75, 23));
        applyedit = new QPushButton(groupBox_3);
        applyedit->setObjectName(QStringLiteral("applyedit"));
        applyedit->setGeometry(QRect(130, 260, 75, 23));
        author_label = new QLabel(groupBox_3);
        author_label->setObjectName(QStringLiteral("author_label"));
        author_label->setGeometry(QRect(10, 100, 51, 16));
        author = new QLineEdit(groupBox_3);
        author->setObjectName(QStringLiteral("author"));
        author->setEnabled(false);
        author->setGeometry(QRect(80, 100, 131, 20));
        loan_label = new QLabel(groupBox_3);
        loan_label->setObjectName(QStringLiteral("loan_label"));
        loan_label->setGeometry(QRect(10, 130, 71, 16));
        loan = new QSpinBox(groupBox_3);
        loan->setObjectName(QStringLiteral("loan"));
        loan->setEnabled(false);
        loan->setGeometry(QRect(80, 130, 42, 22));
        loan_label_2 = new QLabel(groupBox_3);
        loan_label_2->setObjectName(QStringLiteral("loan_label_2"));
        loan_label_2->setGeometry(QRect(130, 130, 61, 16));
        loaner_label = new QLabel(groupBox_3);
        loaner_label->setObjectName(QStringLiteral("loaner_label"));
        loaner_label->setGeometry(QRect(10, 190, 81, 16));
        loaner = new QLabel(groupBox_3);
        loaner->setObjectName(QStringLiteral("loaner"));
        loaner->setGeometry(QRect(90, 190, 111, 16));
        price_label = new QLabel(groupBox_3);
        price_label->setObjectName(QStringLiteral("price_label"));
        price_label->setGeometry(QRect(10, 160, 71, 16));
        price = new QSpinBox(groupBox_3);
        price->setObjectName(QStringLiteral("price"));
        price->setEnabled(false);
        price->setGeometry(QRect(80, 160, 61, 22));
        price->setAccelerated(false);
        price->setMinimum(10);
        price->setMaximum(10000);
        price->setSingleStep(10);
        price->setDisplayIntegerBase(10);
        price_label_2 = new QLabel(groupBox_3);
        price_label_2->setObjectName(QStringLiteral("price_label_2"));
        price_label_2->setGeometry(QRect(150, 160, 51, 16));
        searchbook = new QLineEdit(tab);
        searchbook->setObjectName(QStringLiteral("searchbook"));
        searchbook->setGeometry(QRect(90, 20, 151, 20));
        label_2 = new QLabel(tab);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 20, 81, 16));
        search = new QPushButton(tab);
        search->setObjectName(QStringLiteral("search"));
        search->setGeometry(QRect(250, 20, 75, 23));
        delete_2 = new QPushButton(tab);
        delete_2->setObjectName(QStringLiteral("delete_2"));
        delete_2->setEnabled(false);
        delete_2->setGeometry(QRect(330, 20, 75, 23));
        addbook = new QPushButton(tab);
        addbook->setObjectName(QStringLiteral("addbook"));
        addbook->setGeometry(QRect(260, 300, 75, 23));
        reserve = new QPushButton(tab);
        reserve->setObjectName(QStringLiteral("reserve"));
        reserve->setEnabled(false);
        reserve->setGeometry(QRect(340, 300, 75, 23));
        clearloan = new QPushButton(tab);
        clearloan->setObjectName(QStringLiteral("clearloan"));
        clearloan->setEnabled(false);
        clearloan->setGeometry(QRect(290, 330, 75, 23));
        admintabs->addTab(tab, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        usrreg = new QLabel(tab_3);
        usrreg->setObjectName(QStringLiteral("usrreg"));
        usrreg->setGeometry(QRect(20, 20, 141, 16));
        usrphoto = new QLabel(tab_3);
        usrphoto->setObjectName(QStringLiteral("usrphoto"));
        usrphoto->setGeometry(QRect(20, 80, 161, 16));
        usrinfo = new QLabel(tab_3);
        usrinfo->setObjectName(QStringLiteral("usrinfo"));
        usrinfo->setGeometry(QRect(20, 50, 181, 16));
        usrreg_toggle = new QPushButton(tab_3);
        usrreg_toggle->setObjectName(QStringLiteral("usrreg_toggle"));
        usrreg_toggle->setGeometry(QRect(180, 20, 75, 23));
        label_5 = new QLabel(tab_3);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 340, 251, 16));
        usrinfo_toggle = new QPushButton(tab_3);
        usrinfo_toggle->setObjectName(QStringLiteral("usrinfo_toggle"));
        usrinfo_toggle->setGeometry(QRect(180, 50, 75, 23));
        usrphoto_toggle = new QPushButton(tab_3);
        usrphoto_toggle->setObjectName(QStringLiteral("usrphoto_toggle"));
        usrphoto_toggle->setGeometry(QRect(180, 80, 75, 23));
        admintabs->addTab(tab_3, QString());
        welcome = new QLabel(centralwidget);
        welcome->setObjectName(QStringLiteral("welcome"));
        welcome->setGeometry(QRect(20, 400, 241, 20));
        logout = new QPushButton(centralwidget);
        logout->setObjectName(QStringLiteral("logout"));
        logout->setGeometry(QRect(360, 400, 75, 23));
        logout->setContextMenuPolicy(Qt::DefaultContextMenu);
        Admin->setCentralWidget(centralwidget);
        menubar = new QMenuBar(Admin);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 455, 21));
        Admin->setMenuBar(menubar);

        retranslateUi(Admin);

        admintabs->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Admin);
    } // setupUi

    void retranslateUi(QMainWindow *Admin)
    {
        Admin->setWindowTitle(QApplication::translate("Admin", "Administrator Area - LIMA V1.0", 0));
        actionLogout->setText(QApplication::translate("Admin", "Logout", 0));
        picture->setText(QString());
        changephoto->setText(QApplication::translate("Admin", "Change Photo", 0));
        editprofile->setText(QApplication::translate("Admin", "Edit Profile", 0));
        groupBox->setTitle(QApplication::translate("Admin", "User Information", 0));
        role_label->setText(QApplication::translate("Admin", "User Role:", 0));
        role->setText(QApplication::translate("Admin", "Administrator", 0));
        fine_label->setText(QApplication::translate("Admin", "Fine:", 0));
        fine->setText(QApplication::translate("Admin", "N/A", 0));
        username_label->setText(QApplication::translate("Admin", "Username:", 0));
        username->setText(QApplication::translate("Admin", "TextLabel", 0));
        email->setText(QApplication::translate("Admin", "TextLabel", 0));
        id->setText(QApplication::translate("Admin", "TextLabel", 0));
        name->setText(QApplication::translate("Admin", "TextLabel", 0));
        name_label->setText(QApplication::translate("Admin", "Full Name:", 0));
        email_label->setText(QApplication::translate("Admin", "E-mail:", 0));
        id_label->setText(QApplication::translate("Admin", "ID Number:", 0));
        deleteme->setText(QApplication::translate("Admin", "Delete Account", 0));
        admintabs->setTabText(admintabs->indexOf(UserData), QApplication::translate("Admin", "User Data", 0));
        findid_label->setText(QApplication::translate("Admin", "User ID Number:", 0));
        findid_button->setText(QApplication::translate("Admin", "Search", 0));
        picture_usr->setText(QString());
        groupBox_2->setTitle(QApplication::translate("Admin", "Current User Information", 0));
        role_label_usr->setText(QApplication::translate("Admin", "User Role:", 0));
        role_usr->setText(QString());
        fine_label_usr->setText(QApplication::translate("Admin", "Fine:", 0));
        fine_usr->setText(QApplication::translate("Admin", "N/A", 0));
        username_label_usr->setText(QApplication::translate("Admin", "Username:", 0));
        username_usr->setText(QString());
        email_usr->setText(QString());
        id_usr->setText(QString());
        name_usr->setText(QString());
        fullname_label_usr->setText(QApplication::translate("Admin", "Full Name:", 0));
        email_label_usr->setText(QApplication::translate("Admin", "E-mail:", 0));
        id_label_usr->setText(QApplication::translate("Admin", "ID Number:", 0));
        bookamt_label_usr->setText(QApplication::translate("Admin", "Book Borrowed:", 0));
        bookamt_usr->setText(QApplication::translate("Admin", "N/A", 0));
        booklim_label_usr->setText(QApplication::translate("Admin", "Book Limit:", 0));
        booklim_usr->setText(QApplication::translate("Admin", "N/A", 0));
        changephoto_2->setText(QApplication::translate("Admin", "Change Photo", 0));
        editdata->setText(QApplication::translate("Admin", "Edit Data", 0));
        advanceGrp->setTitle(QApplication::translate("Admin", "Advanced", 0));
        label->setText(QApplication::translate("Admin", "Set Book Limit", 0));
        apply->setText(QApplication::translate("Admin", "Apply", 0));
        label_4->setText(QApplication::translate("Admin", "Set Borrow", 0));
        label_3->setText(QApplication::translate("Admin", "Set Fine", 0));
        deleteusr->setText(QApplication::translate("Admin", "Delete User", 0));
        clear->setText(QApplication::translate("Admin", "Clean User Book Record", 0));
        admintabs->setTabText(admintabs->indexOf(tab_2), QApplication::translate("Admin", "Edit Accounts", 0));
        picture_book->setText(QString());
        changebookphoto->setText(QApplication::translate("Admin", "Change Photo", 0));
        groupBox_3->setTitle(QApplication::translate("Admin", "Book Details", 0));
        bookname_label->setText(QApplication::translate("Admin", "Book Name:", 0));
        ISBN_label->setText(QApplication::translate("Admin", "Book ISBN:", 0));
        bookid_labe->setText(QApplication::translate("Admin", "Book ID:", 0));
        bookid->setText(QApplication::translate("Admin", "Please search for a book.", 0));
        edit->setText(QApplication::translate("Admin", "Edit Data", 0));
        applyedit->setText(QApplication::translate("Admin", "Apply Edit", 0));
        author_label->setText(QApplication::translate("Admin", "Author:", 0));
        loan_label->setText(QApplication::translate("Admin", "Loan Period:", 0));
        loan_label_2->setText(QApplication::translate("Admin", "Days", 0));
        loaner_label->setText(QApplication::translate("Admin", "Current Loaner:", 0));
        loaner->setText(QApplication::translate("Admin", "TextLabel", 0));
        price_label->setText(QApplication::translate("Admin", "Book Price:", 0));
        price_label_2->setText(QApplication::translate("Admin", "THB", 0));
        label_2->setText(QApplication::translate("Admin", "Enter Book ID:", 0));
        search->setText(QApplication::translate("Admin", "Search", 0));
        delete_2->setText(QApplication::translate("Admin", "Delete Book", 0));
        addbook->setText(QApplication::translate("Admin", "Add Book", 0));
        reserve->setText(QApplication::translate("Admin", "Reserve", 0));
        clearloan->setText(QApplication::translate("Admin", "Clear Loaner", 0));
        admintabs->setTabText(admintabs->indexOf(tab), QApplication::translate("Admin", "Edit Books", 0));
        usrreg->setText(QApplication::translate("Admin", "Allow New User Registration:", 0));
        usrphoto->setText(QApplication::translate("Admin", "User Can change Photo:", 0));
        usrinfo->setText(QApplication::translate("Admin", "User Can edit Information:", 0));
        usrreg_toggle->setText(QApplication::translate("Admin", "Enabled", 0));
        label_5->setText(QApplication::translate("Admin", "Press on the button to toggle the setting.", 0));
        usrinfo_toggle->setText(QApplication::translate("Admin", "Enabled", 0));
        usrphoto_toggle->setText(QApplication::translate("Admin", "Enabled", 0));
        admintabs->setTabText(admintabs->indexOf(tab_3), QApplication::translate("Admin", "Advance Settings", 0));
        welcome->setText(QApplication::translate("Admin", "Welcome, message", 0));
        logout->setText(QApplication::translate("Admin", "Log Out", 0));
    } // retranslateUi

};

namespace Ui {
    class Admin: public Ui_Admin {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ADMIN_H
